"""Added last score column

Revision ID: 757aaed7f562
Revises: b5f9a47a31ff
Create Date: 2024-06-18 13:19:45.003328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757aaed7f562'
down_revision: Union[str, None] = 'b5f9a47a31ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoomUser', sa.Column('last_score', sa.Integer(), nullable=True))
    op.drop_column('RoomUser', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoomUser', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"RoomUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('RoomUser', 'last_score')
    # ### end Alembic commands ###
