"""Change defualt value in right answers

Revision ID: b5f9a47a31ff
Revises: e0f0fd24c07b
Create Date: 2024-06-18 10:28:51.415420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f9a47a31ff'
down_revision: Union[str, None] = 'e0f0fd24c07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
