"""Added time of activity creation

Revision ID: c5611734880d
Revises: 4ba5e52ca5e3
Create Date: 2024-05-31 12:57:42.280548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5611734880d'
down_revision: Union[str, None] = '4ba5e52ca5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Activity', 'created_at')
    # ### end Alembic commands ###
