"""Make right answers default value

Revision ID: e0f0fd24c07b
Revises: 4e7f3d1946ee
Create Date: 2024-06-17 16:53:42.525443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f0fd24c07b'
down_revision: Union[str, None] = '4e7f3d1946ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
